# Generated by Django 6.0 on 2025-12-24 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='core.board'),
        ),
        migrations.AddField(
            model_name='pin',
            name='image',
            field=models.ImageField(default=1, upload_to='pins/'),
            preserve_default=False,
        ),
    ]
