# Generated by Django 6.0 on 2025-12-26 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_board_created_at_board_user_alter_board_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='created_at',
        ),
        migrations.AddField(
            model_name='pin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.board'),
        ),
    ]
