# Generated by Django 6.0 on 2025-12-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pin_created_at_alter_pin_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='save_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pin',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
